config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "registration#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :carts, only: [:create, :index, :destroy]
  post 'buy', to: 'carts#buy'

  resources :purchases, only: [:show, :index]

  resources :all_products
  get 'all_products/index'

  resources :products
  get 'products/index'
  get 'products/detail'
  get 'products/all'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'

  authenticate :user do
    resources :products
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :purchases
  has_many :purchasers, through: :purchases, source: :user
  has_many :carts
  has_many :cart_users, through: :carts, source: :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_many :purchases
  has_many :purchased_products, through: :purchases, source: :product
  has_many :carts
  has_many :cart_products, through: :carts, source: :product
  
  devise :database_authenticatable, 
  :registerable,
  :recoverable, 
  :rememberable, 
  :validatable

  validates :first_name, :last_name, 
  presence: true, length: { maximum: 100 }
  
  validates :email, 
  presence: true, length: { maximum: 150 }, 
  format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/all_products_controller.rb
class AllProductsController < ApplicationController
    def index
        @products = Product.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @cart_products = current_user.cart_products
    end

    def create
        @cart = current_user.carts.build(product_id: params[:product_id])
        if @cart.save
            flash[:notice] = 'Product was successfully added to cart.'
            redirect_to all_products_path(params[:product_id]), notice: 'Product was successfully added to cart.'
        else
            redirect_to product_path(params[:product_id]), alert: 'There was an error adding the product to the cart.'
        end
    end

    def buy
        current_user.carts.each do |cart|
          Purchase.create(user: current_user, product: cart.product)
          cart.product.update(sold: true) # помечаем продукт как проданный
          cart.destroy
        end
        # обработка покупки
    end

    def destroy
        @cart = Cart.find_by(user_id: current_user.id, product_id: params[:id])
        @cart.destroy if @cart
        # обработка удаления товара из корзины
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
  end

  def detail
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    end
  end
  
  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end 
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end
  
  def check
    if current_user.role == 'buyer' or @product.user_id == current_user.id
      redirect_to root_path, alert: "Успокойся, малой :)"
    end
  end
  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :rating, :avatar)
  end

end
  

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    def index
        @purchases = current_user.purchases
    end
    
      def show
        @purchase = Purchase.find(params[:id])
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    #изменение данных
    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
    end

    protected
    #ввод данных
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
    
    def update_resource (resource,params)
        return super if params["password"]&.present?
    
        resource.update_without_password(params.except "current_password")
    end

    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def change_role_to_seller
        @user = User.find(params[:id])
        authorize @user, :change_role_to_seller?
        @user.update(role: "seller")
        redirect_to @user, notice: "User role changed to seller"
    end
    
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user! 

end

app/helpers/all_products_helper.rb
module AllProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<h1>Your Cart</h1>

<% if @cart_products.empty? %>
  <p>Your cart is empty</p>
<% else %>
  <% @cart_products.each do |product| %>
    <div>
      <p><%= product.name %></p> 
      <%= button_to "Remove from Cart", cart_path(product), method: :delete %>
    </div>
  <% end %>
  <%= button_to "Buy Now", buy_path, method: :post %>
<% end %>

<%= link_to 'Back', all_products_path(), style: "back_btn" %>

app/views/products/all.html.erb
<div class="product_header">
  <h1> PRODUCTS <h1>
</div>
<hr/>
<% @products.each do |product| %>
  <div class = "product_image-container">
    <p><%= product.name %></p> 
     <br/>
  <%=# link_to "Show Product", product_path(product), class: "product_show-btn" %>
     </div>
<% end %>

app/views/products/create.html.erb
<h1>Create Product</h1>

<%= form_for @product, html: { multipart: true } do |f| %>
<% user_id = current_user.id%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path, style: "back_btn" %>

app/views/products/detail.html.erb
<div class="product_header">
<h1 >PRODUCT.</h1>
</div>
<hr/>
    <div class = "product">
        <div class= "product_text">
            <div class = "product_name">
                <h2>NAME</h2>
                <p><%= @product.name %></p>
                <hr/>
            </div>
            <div class="product_description">
                <h2>DESCRIPTION</h2>
                <p><%= @product.description %></p>
                <hr/>
            </div>
            <div class="product_price">
                <h2>PRICE</h2>
                <p><%= @product.price %></p>
                <hr/>
            </div>
        </div>
    </div>
<%=# link_to "Buy", edit_product_path, class: "product_edit" %>
<br/>
<%= link_to 'Back', products_path, style: "back_btn" %>

app/views/products/edit.html.erb
<h1>EDIT PRODUCT</h1>
<hr/>

<%= form_for @product, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div><%= button_to "Delete", product_path(@product), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class:"cancel-account"%></div>

<%= link_to 'Back', products_path, style: "back_btn" %>

app/views/products/index.html.erb
<div class="product_header">
  <h1> YOUR PRODUCTS <h1>
</div>
<hr/>
<% current_user.products.each do |product| %>
  <div class = "product_image-container">
    <p><%= product.name %></p> 
  <%= link_to "Show Product", product_path(product), class: "product_show-btn" %>
     </div>
     <br/>
<% end %>
<br/>
<%= link_to "Create Product", products_new_path, class: "product_create-btn" %>
<br/>
<br/>
<%= link_to "Back to profile", root_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path, style: "back_btn" %>

app/views/products/show.html.erb
<div class="product_header">
<h1 >PRODUCT</h1>
</div>
<hr/>
    <div class = "product">
        <div class= "product_text">
            <div class = "product_name">
                <h2>NAME</h2>
                <p><%= @product.name %></p>
                <hr/>
            </div>
            <div class="product_description">
                <h2>DESCRIPTION</h2>
                <p><%= @product.description %></p>
                <hr/>
            </div>
            <div class="product_price">
                <h2>PRICE</h2>
                <p><%= @product.price %></p>
                <hr/>
            </div>
        </div>
    </div>

    <% if current_user.id == @product.user_id %>
        <%= link_to "Edit Product", edit_product_path, class: "product_edit" %>
        <%= link_to 'Back', products_path, style: "back_btn" %>
    <% else %>
        <% if @product.sold == true%>
            <p> SOLD </p>
        <% else %>
            <%= button_to "Add to Cart", carts_path(product_id: @product.id), method: :post %>
        <% end %>
        <%= link_to 'Back', all_products_path(), style: "back_btn" %>
    <% end %> 
<br/>


    
    
  